version: "3.1"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USERNAME: "postgres"
      POSTGRES_DB: "dev_connect"
    ports:
      - 5432:5432
    volumes:
      - ./docker-data/db:/var/lib/postgresql/data
